<?php

namespace Tritoq\Bundle\TpanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VhostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VhostRepository extends EntityRepository
{
    public function getByIdDesc () {
        $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.id', 'desc');
        return $qb->getQuery()->getResult();
    }
}
